### ISSUE TITLE
Add remote client support

### ISSUE THREAD

**Issue by igorer88** [mtgto/Fomalhaut2#12]
Hi! I wonder if you have thoughts about having the web sharing feature inverted?
Instead of sharing the local library as a server, it would be nice to connect as a client to a remote server or even multiple servers.

I you need help, I would love to contribute.

**Comment by mtgto** [comment]
Many people don't have multiple remote servers, so I don't think your request is a good one.

**Comment by igorer88** [comment]
It' s a shame, because I don't have enough space in my OS Disc to have book collections.
